abstract class NotificationsStates{}
class NotificationsInitialState extends NotificationsStates{}
class NotificationsLoadingState extends NotificationsStates{}
class NotificationsSuccessfulState extends NotificationsStates{}
class NotificationsErrorState extends NotificationsStates{}
class NotificationsErrorDataInputState extends NotificationsStates{}
